# Generated by Django 6.0.5 on 2026-06-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='vedo/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
