# Generated by Django 6.0.5 on 2026-06-11 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protact', '0002_product_file_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='vedo/', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
