# Generated by Django 6.0.5 on 2026-05-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherbek', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sherbek',
            options={'verbose_name': 'Sherbek', 'verbose_name_plural': 'Sherbeklar'},
        ),
        migrations.AddField(
            model_name='sherbek',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sherbek',
            name='gender',
            field=models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='sherbek',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sherbek',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sherbek',
            name='breed',
            field=models.CharField(default='', max_length=100),
        ),
    ]
