# Generated by Django 6.0.5 on 2026-05-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherbek', '0002_alter_sherbek_options_sherbek_email_sherbek_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sherbek',
            options={'verbose_name': 'Sherbek', 'verbose_name_plural': 'Sherbek'},
        ),
        migrations.AddField(
            model_name='sherbek',
            name='Malumot',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
