# Generated by Django 6.0.5 on 2026-05-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherbek', '0003_alter_sherbek_options_sherbek_malumot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sherbek',
            name='Malumot',
        ),
    ]
