# Generated by Django 6.0.5 on 2026-05-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherbek', '0004_remove_sherbek_malumot'),
    ]

    operations = [
        migrations.AddField(
            model_name='sherbek',
            name='Malumot',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
