# Generated by Django 6.0.5 on 2026-05-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherbek', '0005_sherbek_malumot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=46)),
                ('familya', models.CharField(max_length=45)),
                ('yoshi', models.CharField(max_length=300)),
                ('stem_username', models.CharField(max_length=500)),
                ('telegram_username', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'Conter',
                'verbose_name_plural': 'Conter',
            },
        ),
        migrations.DeleteModel(
            name='Sherbek',
        ),
    ]
