# Generated by Django 6.0.5 on 2026-05-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherbek', '0006_conter_delete_sherbek'),
    ]

    operations = [
        migrations.AddField(
            model_name='conter',
            name='raqam',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
