# Generated by Django 6.0.5 on 2026-05-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherbek', '0007_conter_raqam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conter',
            name='yoshi',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
