# Generated by Django 6.0.5 on 2026-05-27 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherbek', '0008_alter_conter_yoshi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conter',
            options={},
        ),
    ]
