# Generated by Django 6.0.5 on 2026-06-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='familya',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
